# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69a87dc8e344b44dbeb58cacf5e04f23b05738334590aa13f08c574184cc681e5ed27dcfe8032a99f61aed85bf0305f591bd8cdc7eb983d40740a19fc75e6dd6

test:
  secret_key_base: d486096bcab84452d7ef9a43877e765b0586b2bd086c79503933551b66a8874ef5fbb9c80bde5f80cca92c73f1cc8935ebd7a519a6eb779b0cef40e6a6ba7a0a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
